name: mdBook

on:
  push:
    branches: [main, master]
    paths: ["book/**", ".github/workflows/mdbook.yml"]
  pull_request:
    paths: ["book/**", ".github/workflows/mdbook.yml"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install mdbook
        uses: taiki-e/install-action@8b3c737da4b541bf0fb5a3e0488ff20535badac9 # v2.82.1
        with:
          tool: mdbook
      - name: Build
        run: mdbook build book
