name: mdBook

on:
  push:
    branches: [main, master]
    paths: ["book/**", ".github/workflows/mdbook.yml"]
  pull_request:
    paths: ["book/**", ".github/workflows/mdbook.yml"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install mdbook
        uses: taiki-e/install-action@c93ccc03e00cd0e08e494f5fd058a6c55a6a1907 # v2.82.8
        with:
          tool: mdbook
      - name: Build
        run: mdbook build book
