name: mdBook

on:
  push:
    branches: [main, master]
    paths: ["book/**", ".github/workflows/mdbook.yml"]
  pull_request:
    paths: ["book/**", ".github/workflows/mdbook.yml"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install mdbook
        uses: taiki-e/install-action@7a79fe8c3a13344501c80d99cae481c1c9085912 # v2.81.10
        with:
          tool: mdbook
      - name: Build
        run: mdbook build book
